# this DB is not persistence
version: '3.8'
services:

  booksdb:
    restart: always
    image: postgres:13
    container_name: booksdb
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: tester
      POSTGRES_PASSWORD: mySuperPass
      POSTGRES_DB: test