# this DB is not persistence
version: '3.8'
services:

  servicedb:
    restart: always
    image: postgres:13
    container_name: servicedb
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: tester
      POSTGRES_PASSWORD: mySuperPass
      POSTGRES_DB: test

  service:
    image: googlebooksimg
    container_name: service
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    restart: always
    ports:
      - 1010:8080
